// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRv-Jle71bcKyV8ZLlCnxUMZWLu8mzHY4',
    appId: '1:1096018405172:web:c94da8734587522c2ae761',
    messagingSenderId: '1096018405172',
    projectId: 'nayr-424409',
    authDomain: 'nayr-424409.firebaseapp.com',
    storageBucket: 'nayr-424409.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL94ROipgUQbpuhn6oKjG3Ngizrhohfs4',
    appId: '1:1096018405172:android:1e2d0c6f347f58412ae761',
    messagingSenderId: '1096018405172',
    projectId: 'nayr-424409',
    storageBucket: 'nayr-424409.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF96eZmaXmGZnJ96q-jcAE1zc-G1Y79Y4',
    appId: '1:1096018405172:ios:4578b62feaab65cc2ae761',
    messagingSenderId: '1096018405172',
    projectId: 'nayr-424409',
    storageBucket: 'nayr-424409.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF96eZmaXmGZnJ96q-jcAE1zc-G1Y79Y4',
    appId: '1:1096018405172:ios:4578b62feaab65cc2ae761',
    messagingSenderId: '1096018405172',
    projectId: 'nayr-424409',
    storageBucket: 'nayr-424409.appspot.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRv-Jle71bcKyV8ZLlCnxUMZWLu8mzHY4',
    appId: '1:1096018405172:web:51f6b4e09a8e415b2ae761',
    messagingSenderId: '1096018405172',
    projectId: 'nayr-424409',
    authDomain: 'nayr-424409.firebaseapp.com',
    storageBucket: 'nayr-424409.appspot.com',
  );
}
